#!/usr/bin/env bash
# Regenerate `split.css` from the shipped sources. Run from the repo root.
#
#   bash docs/visual/concepts/mockups/src/build-css.sh
#   node docs/visual/concepts/mockups/src/shoot.mjs
#
# `split.css` is three concatenated parts and NOTHING is hand-edited in it:
#   1. index.html's `:root` token block            (verbatim)
#   2. overhaul.css's `#screen-briefing` section   (verbatim, lines 1254-2551)
#   3. split.overrides.css                         (the only new CSS)
# So `diff <(sed -n '1254,2551p' src/render/overhaul.css) <(sed -n '<part2>' …)`
# is empty by construction, and every visual difference between this mockup and
# the shipped screen is in part 3 and nowhere else.
set -euo pipefail
cd "$(dirname "$0")/../../../../.."

D=docs/visual/concepts/mockups/src
FIRST=1254   # `/* ═══ THE OVERHAUL LOOK — BRIEFING SCREEN` in src/render/overhaul.css
LAST=2551    # end of file

grep -q 'THE OVERHAUL LOOK — BRIEFING SCREEN' <(sed -n "${FIRST}p;$((FIRST+1))p" src/render/overhaul.css) \
  || { echo "overhaul.css moved: line $FIRST is no longer the briefing banner" >&2; exit 1; }

{
  echo "/* GENERATED by src/build-css.sh — do not hand-edit."
  echo "   1: index.html :root tokens · 2: overhaul.css ${FIRST}-${LAST} · 3: split.overrides.css */"
  echo
  sed -n '/^      :root {/,/^      }$/p' index.html | head -70 | sed 's/^      //'
  echo
  echo "* { box-sizing: border-box; }"
  echo "html, body { margin: 0; height: 100%; overflow: hidden; background: var(--bg); }"
  echo
  sed -n "${FIRST},${LAST}p" src/render/overhaul.css
  echo
  cat "$D/split.overrides.css"
} > "$D/split.css"

echo "wrote $D/split.css ($(wc -l < "$D/split.css") lines)"
