/**
 * Single source for the NON-DERIVABLE prose of the "State of the Engine" dashboard
 * (`state/index.html`, generated by `scripts/gen-state.mts`).
 *
 * Everything countable — jobs, abilities, builds, ADRs, sim modules, and the LIVE
 * diversity-gate matrix — is derived from the repo by the generator and must NOT be
 * hand-typed here. This module holds only the editorial copy the filesystem cannot
 * infer: the phase/status line, the section lead paragraphs, the systems-board card
 * bodies, the roadmap phases, and the "what's next" moves.
 *
 * To bump the phase, re-word a lead, or re-order the roadmap: edit THIS file, then run
 * `npm run state` to regenerate. Numbers self-update; prose is single-sourced here.
 *
 * Prose strings are trusted, committed HTML fragments (inline <b>/<em>/<span> allowed).
 * A `{token}` placeholder (e.g. `{jobs}`, `{modules}`, `{skillsets}`) is substituted
 * with a live-derived value by the generator — keep the count out of the prose, keep
 * only its POSITION.
 */

export interface RoadmapPhase {
  id: string;
  title: string;
  blurb: string;
  /** Timeline state — drives the card styling. */
  state: "done" | "active" | "next";
  tag: string;
  tagClass: "ok" | "accent" | "plan";
}

export interface NextStep {
  rank: string;
  title: string;
  /** An inline badge next to the title (e.g. "recommended"), or null. */
  badge: string | null;
  body: string;
  chip: string;
  /** Highlights the card as the recommended move. */
  recommended: boolean;
}

export interface SpineCell {
  n: string;
  k: string;
  sub: string;
}

export interface SystemCard {
  title: string;
  /** Mono sub-label after the title (may carry a `{token}`), or null. */
  signature: string | null;
  body: string;
  /** Mono detail line (may carry a `{token}`), or null. */
  detail: string | null;
  pillClass: "ok" | "warn" | "accent" | "plan";
  pillLabel: string;
}

export const content = {
  eyebrow: "State of the Engine",
  title: "The Unseen Hand",
  lede:
    'A turn-based tactics engine in the lineage of <em>Final Fantasy Tactics: War of the Lions</em> ' +
    "— built spine-first around a deep job &amp; customization system. Narrative is a separate, " +
    "not-yet-started repo; this codebase stays content-agnostic and loads battles as data.",

  /** The one-line phase/status. Bump the phase here. */
  status: {
    phase: "PHASE P2 · CUSTOMIZATION DEPTH",
    prePill: "PRE-CONTENT",
  },

  /** Section lead paragraphs (in render order). */
  leads: {
    whereItStands:
      "The <b>simulation core is real and green</b>: a full, deterministic combat engine with a " +
      "headless balance harness. The <b>viewer is intentionally behind it</b> — it draws movement and " +
      "turn order but not yet attacks. There is <b>no narrative or long-form content</b>; that's by " +
      "design for this phase.",
    architecture:
      "One rule governs the shape: <b>the sim is pure and headless</b> (ADR-0007). Determinism is a P0 " +
      "invariant — a single seeded PRNG drives every roll in a declared order, so a battle is " +
      'byte-for-byte reproducible from <span class="mono">(seed, commands)</span>. That\'s what makes ' +
      "rewind, saves, and shareable build codes possible.",
    spine:
      "The whole game is organized around one locked design decision (ADR-0001): depth comes from " +
      "<b>three customization axes</b>, and success is measured in <em>meaningfully different, viable " +
      "builds</em> — not in the number of options. Everything else is optional or deferred.",
    spineRespec:
      "Respec is free and progress is permanent — learned abilities and masteries are never lost, " +
      "loadout swaps cost nothing (ADR-0002). Experiments are safe by design; specialization still " +
      "costs a generalization (the anti-convergence law).",
    gate:
      "This is the pillar's safety net and the most recent work. A <b>substitution gauntlet</b> fields " +
      "each reference build across the shipped maps against distinct <em>threat</em> profiles, and " +
      "checks two things: enough <b>distinct viable identities</b> land their signature, and <b>no build " +
      "strictly outclasses the field</b>. It fields two opposition axes — physical and magic — so a build " +
      "can finally <em>lose to something</em> (real opportunity cost), not just win everywhere. The table " +
      "below is regenerated from a live gauntlet run every time this page is built.",
    gateHonesty:
      "* Honesty note: the magic axis is a real second threat that makes cost non-uniform, but on the " +
      "aggregate roster it rewards tempo/range as much as personal Faith — the anti-mage's <em>own</em> " +
      "magic resistance can't save its Faith-50 allies without support-aware AI, so it still shows a " +
      "team-level magic loss. The isolated Faith cliff is proved by a separate must-fail straddle test. " +
      'The <span class="mono">8-archetype</span> release bar (AC-E2) stays the goal; N rises as new jobs ' +
      "and AI capabilities land.",
    roadmap:
      "Foundational invariants shipped first, UI later. Two phases are behind us; we're mid-way through " +
      "the third — the one that <em>is</em> the pillar.",
    next:
      "Several reference builds are still <em>unmeasured</em> because the greedy 1-ply probe can't " +
      "exercise their identities yet — each is tagged in the manifest with the capability that unblocks " +
      "it. The moves, by leverage:",
  },

  /** The four systems-board cards. `{modules}`, `{jobs}`, `{abilities}`, `{builds}`, `{maps}`, `{skillsets}` are live-injected. */
  systems: [
    {
      title: "Simulation core",
      signature: "src/sim · {modules} modules",
      body:
        "CT-tick scheduler with pinned tie-break, hit/damage/status/crit resolution, charged actions, " +
        "area abilities, the greedy balance-probe AI, seeded RNG, and a serializable battle state that " +
        "backs both saves and rewind.",
      detail: "scheduler · resolve · formulas · charge · aoe · status · ai · rng · state · codec",
      pillClass: "ok",
      pillLabel: "LIVE",
    },
    {
      title: "Viewer",
      signature: "src/render",
      body:
        "A deliberately thin isometric renderer over the sim (imports it, never the reverse). Shows the " +
        "grid with height, unit facing/HP, move-range highlight, and the turn-order timeline. Attack " +
        "animation &amp; the loadout menus come later.",
      detail: "iso projection · step/reset · turn timeline · Playwright visual gallery",
      pillClass: "warn",
      pillLabel: "PARTIAL",
    },
    {
      title: "Content &amp; data",
      signature: "data/",
      body:
        "{jobs} jobs, {abilities} abilities, statuses and traits — all schema-validated data, not " +
        "hard-code. {builds} reference unit builds and a {maps}-map benchmark suite exist to <em>test " +
        "balance</em>, not to be a campaign.",
      detail: "{skillsets}",
      pillClass: "accent",
      pillLabel: "SEED SET",
    },
    {
      title: "Narrative &amp; campaign",
      signature: null,
      body:
        "Story lives in a separate repo that hasn't begun. The engine already exposes the " +
        "battle-definition data contract it will consume, so story battles can slot in with no engine " +
        "change when that work starts.",
      detail: "docs/08 §4 — map · spawns · victory/defeat · events · loot · seed",
      pillClass: "plan",
      pillLabel: "NOT STARTED",
    },
  ] satisfies SystemCard[],

  /** The three customization-spine cells. */
  spineCells: [
    { n: "5+2", k: "Ability chassis", sub: "primary · secondary · reaction · support · movement (+traits)" },
    { n: "AP", k: "Job / skill trees", sub: "directed progression · permanent mastery bonuses" },
    { n: "×", k: "Hybrid / fusion jobs", sub: "the recombination layer — curated, not the full N² web" },
  ] satisfies SpineCell[],

  /** KPI tiles (labels only — values are derived). Order is the render order. */
  kpis: [
    { key: "jobs", label: "Jobs" },
    { key: "abilities", label: "Abilities" },
    { key: "traitsStatus", label: "Traits+Status" },
    { key: "builds", label: "Unit builds" },
    { key: "encounters", label: "Encounters" },
    { key: "adrs", label: "ADRs" },
  ],

  /** Roadmap phases (P0→P4). */
  roadmap: [
    { id: "P0", title: "Core loop", blurb: "Grid · CT scheduler · seeded RNG · serializable state · formula vectors.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P1", title: "Chassis + data", blurb: "5-slot loadout · data-driven schemas · AP purchase · base job set.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P2", title: "Customization depth", blurb: "Trees · mastery · respec · <b>the diversity gate</b> — the balance safety net.", state: "active", tag: "IN PROGRESS", tagClass: "accent" },
    { id: "P3", title: "Enhancements", blurb: "Hybrid/fusion jobs · rewind UI · scan · speed toggle.", state: "next", tag: "PLANNED", tagClass: "plan" },
    { id: "P4", title: "Content &amp; polish", blurb: "Encounter suite · balance passes · difficulty · onboarding · sharing.", state: "next", tag: "PLANNED", tagClass: "plan" },
  ] satisfies RoadmapPhase[],

  /** "What's next" — ordered by leverage. */
  nextSteps: [
    {
      rank: "01",
      title: "Support-aware AI",
      badge: "recommended",
      body:
        "The biggest single unlock: moves the summoner + both clerics from excluded to measurable (N " +
        "toward ~7), lets the anti-mage protect its allies so its identity is real in the gate, and opens " +
        "the Defend / Escort encounter archetypes.",
      chip: "+3 builds",
      recommended: true,
    },
    {
      rank: "02",
      title: "A third threat axis (mixed opposition)",
      badge: null,
      body:
        "Small and self-contained. With three distinct axes, anti-convergence can move from " +
        "<em>surfaced</em> to <em>enforced</em> — a build with no losing matchup becomes a meaningful " +
        "signal rather than a coverage gap.",
      chip: "tighten gate",
      recommended: false,
    },
    {
      rank: "03",
      title: "Provoke / threat &amp; reaction-as-live",
      badge: null,
      body:
        "Independent medium slices: a threat mechanic unlocks the aggro-tank; modeling reactions as live " +
        "actions unlocks the counter-wall and reraise-cleric. Each retires named manifest exclusions.",
      chip: "+1–3 builds",
      recommended: false,
    },
  ] satisfies NextStep[],

  /** Static footer bits (the ADR count is appended live). */
  footer: ["the-unseen-hand-turn-based", "· TypeScript · Vitest · Zod · Vite", "· determinism = P0", "· docs/ is the source of truth"],
} as const;
