/**
 * Single source for the NON-DERIVABLE prose of the "State of the Engine" dashboard
 * (`state/index.html`, generated by `scripts/gen-state.mts`).
 *
 * Everything countable — jobs, abilities, builds, ADRs, sim modules, and the LIVE
 * diversity-gate matrix — is derived from the repo by the generator and must NOT be
 * hand-typed here. This module holds only the editorial copy the filesystem cannot
 * infer: the phase/status line, the section lead paragraphs, the systems-board card
 * bodies, the roadmap phases, and the "what's next" moves.
 *
 * To bump the phase, re-word a lead, or re-order the roadmap: edit THIS file, then run
 * `npm run state` to regenerate. Numbers self-update; prose is single-sourced here.
 *
 * Prose strings are trusted, committed HTML fragments (inline <b>/<em>/<span> allowed).
 * A `{token}` placeholder (e.g. `{jobs}`, `{modules}`, `{skillsets}`) is substituted
 * with a live-derived value by the generator — keep the count out of the prose, keep
 * only its POSITION.
 *
 * ⚠ THE CI DRIFT CHECK DOES NOT VALIDATE THIS FILE'S CLAIMS. It regenerates
 * `state/index.html` from this module and fails if the committed page differs — which
 * proves the PAGE MATCHES THIS SOURCE, not that this source matches reality. Everything
 * here is hand-authored: the phase line, the roadmap `state` flags, the "what's next"
 * ordering. A phase marked `done` stays marked `done` until a human corrects it, and the
 * check looks identical either way (CLAUDE.md, the evidence principle). This has bitten
 * twice: a status header claimed "pre-code" against 428 passing tests, and a later one
 * claimed P3 while P3's own deliverables were unshipped. When you touch the roadmap here,
 * reconcile it against `docs/08` §1a and against the code — not against memory.
 */

export interface RoadmapPhase {
  id: string;
  title: string;
  blurb: string;
  /** Timeline state — drives the card styling. */
  state: "done" | "active" | "next";
  tag: string;
  tagClass: "ok" | "accent" | "plan";
}

export interface NextStep {
  rank: string;
  title: string;
  /** An inline badge next to the title (e.g. "recommended"), or null. */
  badge: string | null;
  body: string;
  chip: string;
  /** Highlights the card as the recommended move. */
  recommended: boolean;
}

export interface SpineCell {
  n: string;
  k: string;
  sub: string;
}

export interface SystemCard {
  title: string;
  /** Mono sub-label after the title (may carry a `{token}`), or null. */
  signature: string | null;
  body: string;
  /** Mono detail line (may carry a `{token}`), or null. */
  detail: string | null;
  pillClass: "ok" | "warn" | "accent" | "plan";
  pillLabel: string;
}

export const content = {
  eyebrow: "State of the Engine",
  title: "The Unseen Hand",
  lede:
    'A turn-based tactics engine in the lineage of <em>Final Fantasy Tactics: War of the Lions</em> ' +
    "— built spine-first around a deep job &amp; customization system. Narrative is a separate, " +
    "not-yet-started repo; this codebase stays content-agnostic and loads battles as data.",

  /** The one-line phase/status. Bump the phase here. */
  status: {
    phase: "MILESTONE M0 · THE PLAYABLE SLICE",
    prePill: "PRE-CONTENT",
  },

  /** Section lead paragraphs (in render order). */
  leads: {
    whereItStands:
      "The <b>simulation core is real and green</b>: a full, deterministic combat engine with a " +
      "headless balance harness, a playable click-to-act viewer, and — new — a <b>playable campaign</b>: " +
      "{campaignBattles} battles in order, a party that keeps what it earns, and a title screen with a " +
      "save slot in the browser (<b>ADR-0022</b>, <b>ADR-0023</b>). You can start it, play it and finish " +
      "it. What is still missing is the depth around it: no between-battle prep loop, no story text, no " +
      "equipment. There is <b>no narrative content</b>; that is by design.",
    architecture:
      "One rule governs the shape: <b>the sim is pure and headless</b> (ADR-0007). Determinism is a P0 " +
      "invariant — a single seeded PRNG drives every roll in a declared order, so a battle is " +
      'byte-for-byte reproducible from <span class="mono">(seed, commands)</span>. That\'s what makes ' +
      "rewind, saves, and shareable build codes possible.",
    spine:
      "The whole game is organized around one locked design decision (ADR-0001): depth comes from " +
      "<b>three customization axes</b>, and success is measured in <em>meaningfully different, viable " +
      "builds</em> — not in the number of options. Everything else is optional or deferred.",
    spineRespec:
      "Respec is free and progress is permanent — learned abilities and masteries are never lost, " +
      "loadout swaps cost nothing (ADR-0002). Experiments are safe by design; specialization still " +
      "costs a generalization (the anti-convergence law).",
    gate:
      "This is the pillar's safety net and the most recent work. A <b>substitution gauntlet</b> fields " +
      "each reference build across the shipped maps against distinct <em>threat</em> profiles, and " +
      "checks two things: enough <b>distinct viable identities</b> land their signature, and <b>no build " +
      "strictly outclasses the field</b>. It fields two opposition axes — physical and magic — so a build " +
      "can finally <em>lose to something</em> (real opportunity cost), not just win everywhere. The table " +
      "below is regenerated from a live gauntlet run every time this page is built. The newest identity is " +
      "the <b>Cutpurse</b>, whose signature deals no damage at all: it <em>charms</em>, and a charmed unit " +
      "fights for whoever charmed it (<b>ADR-0018</b>). The <b>Counter Wall</b> joined the measured field " +
      "when reactions went live (<b>ADR-0019</b>) &mdash; and it adds <em>zero</em> to the variety score, " +
      "because it shares the monk's <span class=\"mono\">punch-art.</span> family. A retired blocker does " +
      "not owe the count a point.",
    gateHonesty:
      "* Honesty note: the magic axis is a real second threat that makes cost non-uniform, but on the " +
      "aggregate roster it rewards tempo/range as much as personal Faith — the anti-mage's <em>own</em> " +
      "magic resistance can't save its Faith-50 allies without support-aware positioning, so it still shows " +
      "a team-level magic loss. The isolated Faith cliff is proved by a separate must-fail straddle test. " +
      'The <span class="mono">8-archetype</span> release bar (AC-E2) stays the goal; N rises as new jobs ' +
      "and AI capabilities land.",
    roadmap:
      "Foundational invariants shipped first, UI later. Two phases are behind us; we're mid-way through " +
      "the third — the one that <em>is</em> the pillar. <b>The work has moved off this list for now:</b> " +
      "the current slice is <b>M0, the playable MVP</b> (the <em>game</em> roadmap, not the engine one), " +
      "and P2's two open items — the variety score reaching 8, and MP enforcement — are carried into M1 " +
      "by an explicit decision. They are not weakened; only their due date moved.",
    next:
      "The MVP comes first: a stranger should be able to start the game, play 30&ndash;45 minutes and " +
      "reach a real ending. That path now exists end to end &mdash; what it lacks is anything to decide " +
      "<em>between</em> battles, and a word of story. After that, the engine backlog resumes. The moves, " +
      "by leverage:",
  },

  /** The four systems-board cards. `{modules}`, `{jobs}`, `{abilities}`, `{builds}`, `{maps}`, `{skillsets}` are live-injected. */
  systems: [
    {
      title: "Simulation core",
      signature: "src/sim · {modules} modules",
      body:
        "CT-tick scheduler with pinned tie-break, hit/damage/status/crit resolution, charged actions, " +
        "area abilities, the greedy balance-probe AI, seeded RNG, and a serializable battle state that " +
        "backs both saves and rewind.",
      detail: "scheduler · resolve · formulas · charge · aoe · status · ai · rng · state · codec",
      pillClass: "ok",
      pillLabel: "LIVE",
    },
    {
      title: "Viewer &amp; shell",
      signature: "src/render",
      body:
        "A deliberately thin isometric renderer over the sim (imports it, never the reverse). Two pages: " +
        "the <b>engine viewer</b> (one demo battle, every internal number on show) and <b>the game</b> " +
        "&mdash; title screen, New Game / Continue, one save slot in the browser, and the campaign's own " +
        "battles in between (<b>ADR-0023</b>). Attack animation and the between-battle prep loop come later.",
      detail: "iso projection · turn timeline · save slot · title → battle → ending · Playwright gallery",
      pillClass: "warn",
      pillLabel: "PARTIAL",
    },
    {
      title: "Content &amp; data",
      signature: "data/",
      body:
        "{jobs} jobs, {abilities} abilities, statuses and traits — all schema-validated data, not " +
        "hard-code. {builds} reference unit builds and a {maps}-map benchmark suite exist to <em>test " +
        "balance</em>, not to be a campaign.",
      detail: "{skillsets}",
      pillClass: "accent",
      pillLabel: "SEED SET",
    },
    {
      title: "Narrative &amp; campaign",
      signature: null,
      body:
        "A {campaignBattles}-battle campaign now runs end to end, but it carries <em>no prose</em>: it " +
        "references battles by encounter id and nothing else. Story lives in a separate repo that hasn't " +
        "begun. The engine already exposes the battle-definition data contract it will consume, so story " +
        "battles can slot in with no engine change when that work starts.",
      detail: "docs/08 §4 — map · spawns · victory/defeat · events · loot · seed",
      pillClass: "plan",
      pillLabel: "TEXT NOT STARTED",
    },
  ] satisfies SystemCard[],

  /** The three customization-spine cells. */
  spineCells: [
    { n: "5 of 5", k: "Chassis slots live", sub: "primary · secondary · support · reaction · movement — the spine's first axis is complete" },
    { n: "AP", k: "Job / skill trees", sub: "directed progression · permanent mastery bonuses" },
    { n: "×", k: "Hybrid / fusion jobs", sub: "the recombination layer — curated, not the full N² web" },
  ] satisfies SpineCell[],

  /** KPI tiles (labels only — values are derived). Order is the render order. */
  kpis: [
    { key: "jobs", label: "Jobs" },
    { key: "abilities", label: "Abilities" },
    { key: "traitsStatus", label: "Traits+Status" },
    { key: "builds", label: "Unit builds" },
    { key: "encounters", label: "Encounters" },
    { key: "adrs", label: "ADRs" },
  ],

  /** Roadmap phases (P0→P4). */
  roadmap: [
    { id: "P0", title: "Core loop", blurb: "Grid · CT scheduler · seeded RNG · serializable state · formula vectors.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P1", title: "Chassis + data", blurb: "5-slot loadout · data-driven schemas · AP purchase · base job set.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P2", title: "Customization depth", blurb: "Trees · mastery · respec · <b>the diversity gate</b> — the balance safety net.", state: "active", tag: "IN PROGRESS", tagClass: "accent" },
    { id: "P3", title: "Enhancements", blurb: "Hybrid/fusion jobs · rewind UI · scan · speed toggle.", state: "next", tag: "PLANNED", tagClass: "plan" },
    { id: "P4", title: "Content &amp; polish", blurb: "Encounter suite · balance passes · difficulty · onboarding · sharing.", state: "next", tag: "PLANNED", tagClass: "plan" },
  ] satisfies RoadmapPhase[],

  /** "What's next" — ordered by leverage. */
  nextSteps: [
    {
      rank: "01",
      title: "The between-battle loop and the story seam",
      badge: "recommended",
      body:
        "<b>The shell landed</b> (<b>ADR-0023</b>): a title screen, New Game and Continue, one save slot in " +
        "the browser, the real battle in between, and a lost fight that becomes a retryable game-over. A " +
        "person can now start the campaign and finish it. What they cannot do is <em>make a decision</em> " +
        "between battles &mdash; the prep screen already equips abilities and traits, it is just not " +
        "reachable from the briefing. Routing it through <span class=\"mono\">updatePartyMember</span> is " +
        "cheap. Battle text lands beside it as <em>data</em> &mdash; placeholder prose in the narrative-repo " +
        "contract shape, so the seam is real before anyone writes a word of story.",
      chip: "MVP",
      recommended: true,
    },
    {
      rank: "02",
      title: "Teach the AI to hold a line",
      badge: null,
      body:
        "<b>The AI now avoids standing where enemies can reach it</b> (<b>ADR-0020</b>) &mdash; which is " +
        "what finally made the fifth equip slot shippable, and it improved the anti-convergence numbers " +
        "as a side effect. But it knows exactly one thing about danger: <em>how many enemies could hit " +
        "this tile</em>. It has no notion of holding a chokepoint, screening a wounded ally, or trading a " +
        "risky square for a decisive one. Deferred to M1 with the rest of the engine backlog; watch for " +
        "stalemates when it lands, since a battle that never ends reads in the results table exactly " +
        "like a loss.",
      chip: "AI depth",
      recommended: false,
    },
  ] satisfies NextStep[],

  /** Static footer bits (the ADR count is appended live). */
  footer: ["the-unseen-hand-turn-based", "· TypeScript · Vitest · Zod · Vite", "· determinism = P0", "· docs/ is the source of truth"],
} as const;
