/**
 * Single source for the NON-DERIVABLE prose of the "State of the Engine" dashboard
 * (`state/index.html`, generated by `scripts/gen-state.mts`).
 *
 * Everything countable — jobs, abilities, builds, ADRs, sim modules, and the LIVE
 * diversity-gate matrix — is derived from the repo by the generator and must NOT be
 * hand-typed here. This module holds only the editorial copy the filesystem cannot
 * infer: the phase/status line, the section lead paragraphs, the systems-board card
 * bodies, the roadmap phases, and the "what's next" moves.
 *
 * To bump the phase, re-word a lead, or re-order the roadmap: edit THIS file, then run
 * `npm run state` to regenerate. Numbers self-update; prose is single-sourced here.
 *
 * Prose strings are trusted, committed HTML fragments (inline <b>/<em>/<span> allowed).
 * A `{token}` placeholder (e.g. `{jobs}`, `{modules}`, `{skillsets}`) is substituted
 * with a live-derived value by the generator — keep the count out of the prose, keep
 * only its POSITION.
 *
 * ⚠ THE CI DRIFT CHECK DOES NOT VALIDATE THIS FILE'S CLAIMS. It regenerates
 * `state/index.html` from this module and fails if the committed page differs — which
 * proves the PAGE MATCHES THIS SOURCE, not that this source matches reality. Everything
 * here is hand-authored: the phase line, the roadmap `state` flags, the "what's next"
 * ordering. A phase marked `done` stays marked `done` until a human corrects it, and the
 * check looks identical either way (CLAUDE.md, the evidence principle). This has bitten
 * twice: a status header claimed "pre-code" against 428 passing tests, and a later one
 * claimed P3 while P3's own deliverables were unshipped. When you touch the roadmap here,
 * reconcile it against `docs/08` §1a and against the code — not against memory.
 */

export interface RoadmapPhase {
  id: string;
  title: string;
  blurb: string;
  /** Timeline state — drives the card styling. */
  state: "done" | "active" | "next";
  tag: string;
  tagClass: "ok" | "accent" | "plan";
}

export interface NextStep {
  rank: string;
  title: string;
  /** An inline badge next to the title (e.g. "recommended"), or null. */
  badge: string | null;
  body: string;
  chip: string;
  /** Highlights the card as the recommended move. */
  recommended: boolean;
}

export interface SpineCell {
  n: string;
  k: string;
  sub: string;
}

export interface SystemCard {
  title: string;
  /** Mono sub-label after the title (may carry a `{token}`), or null. */
  signature: string | null;
  body: string;
  /** Mono detail line (may carry a `{token}`), or null. */
  detail: string | null;
  pillClass: "ok" | "warn" | "accent" | "plan";
  pillLabel: string;
}

export const content = {
  eyebrow: "State of the Engine",
  title: "The Unseen Hand",
  lede:
    'A turn-based tactics engine in the lineage of <em>Final Fantasy Tactics: War of the Lions</em> ' +
    "— built spine-first around a deep job &amp; customization system. Narrative is a separate, " +
    "not-yet-started repo; this codebase stays content-agnostic and loads battles as data.",

  /** The one-line phase/status. Bump the phase here. */
  status: {
    phase: "PHASE P2 · CUSTOMIZATION DEPTH",
    prePill: "PRE-CONTENT",
  },

  /** Section lead paragraphs (in render order). */
  leads: {
    whereItStands:
      "The <b>simulation core is real and green</b>: a full, deterministic combat engine with a " +
      "headless balance harness. The <b>viewer is intentionally behind it</b> — it draws movement and " +
      "turn order but not yet attacks. There is <b>no narrative or long-form content</b>; that's by " +
      "design for this phase.",
    architecture:
      "One rule governs the shape: <b>the sim is pure and headless</b> (ADR-0007). Determinism is a P0 " +
      "invariant — a single seeded PRNG drives every roll in a declared order, so a battle is " +
      'byte-for-byte reproducible from <span class="mono">(seed, commands)</span>. That\'s what makes ' +
      "rewind, saves, and shareable build codes possible.",
    spine:
      "The whole game is organized around one locked design decision (ADR-0001): depth comes from " +
      "<b>three customization axes</b>, and success is measured in <em>meaningfully different, viable " +
      "builds</em> — not in the number of options. Everything else is optional or deferred.",
    spineRespec:
      "Respec is free and progress is permanent — learned abilities and masteries are never lost, " +
      "loadout swaps cost nothing (ADR-0002). Experiments are safe by design; specialization still " +
      "costs a generalization (the anti-convergence law).",
    gate:
      "This is the pillar's safety net and the most recent work. A <b>substitution gauntlet</b> fields " +
      "each reference build across the shipped maps against distinct <em>threat</em> profiles, and " +
      "checks two things: enough <b>distinct viable identities</b> land their signature, and <b>no build " +
      "strictly outclasses the field</b>. It fields two opposition axes — physical and magic — so a build " +
      "can finally <em>lose to something</em> (real opportunity cost), not just win everywhere. The table " +
      "below is regenerated from a live gauntlet run every time this page is built. The newest identity is " +
      "the <b>Cutpurse</b>, whose signature deals no damage at all: it <em>charms</em>, and a charmed unit " +
      "fights for whoever charmed it (<b>ADR-0018</b>). The <b>Counter Wall</b> joined the measured field " +
      "when reactions went live (<b>ADR-0019</b>) &mdash; and it adds <em>zero</em> to the variety score, " +
      "because it shares the monk's <span class=\"mono\">punch-art.</span> family. A retired blocker does " +
      "not owe the count a point.",
    gateHonesty:
      "* Honesty note: the magic axis is a real second threat that makes cost non-uniform, but on the " +
      "aggregate roster it rewards tempo/range as much as personal Faith — the anti-mage's <em>own</em> " +
      "magic resistance can't save its Faith-50 allies without support-aware positioning, so it still shows " +
      "a team-level magic loss. The isolated Faith cliff is proved by a separate must-fail straddle test. " +
      'The <span class="mono">8-archetype</span> release bar (AC-E2) stays the goal; N rises as new jobs ' +
      "and AI capabilities land.",
    roadmap:
      "Foundational invariants shipped first, UI later. Two phases are behind us; we're mid-way through " +
      "the third — the one that <em>is</em> the pillar.",
    next:
      "Several reference builds are still <em>unmeasured</em> because the greedy 1-ply probe can't " +
      "exercise their identities yet — each is tagged in the manifest with the capability that unblocks " +
      "it. The moves, by leverage:",
  },

  /** The four systems-board cards. `{modules}`, `{jobs}`, `{abilities}`, `{builds}`, `{maps}`, `{skillsets}` are live-injected. */
  systems: [
    {
      title: "Simulation core",
      signature: "src/sim · {modules} modules",
      body:
        "CT-tick scheduler with pinned tie-break, hit/damage/status/crit resolution, charged actions, " +
        "area abilities, the greedy balance-probe AI, seeded RNG, and a serializable battle state that " +
        "backs both saves and rewind.",
      detail: "scheduler · resolve · formulas · charge · aoe · status · ai · rng · state · codec",
      pillClass: "ok",
      pillLabel: "LIVE",
    },
    {
      title: "Viewer",
      signature: "src/render",
      body:
        "A deliberately thin isometric renderer over the sim (imports it, never the reverse). Shows the " +
        "grid with height, unit facing/HP, move-range highlight, and the turn-order timeline. Attack " +
        "animation &amp; the loadout menus come later.",
      detail: "iso projection · step/reset · turn timeline · Playwright visual gallery",
      pillClass: "warn",
      pillLabel: "PARTIAL",
    },
    {
      title: "Content &amp; data",
      signature: "data/",
      body:
        "{jobs} jobs, {abilities} abilities, statuses and traits — all schema-validated data, not " +
        "hard-code. {builds} reference unit builds and a {maps}-map benchmark suite exist to <em>test " +
        "balance</em>, not to be a campaign.",
      detail: "{skillsets}",
      pillClass: "accent",
      pillLabel: "SEED SET",
    },
    {
      title: "Narrative &amp; campaign",
      signature: null,
      body:
        "Story lives in a separate repo that hasn't begun. The engine already exposes the " +
        "battle-definition data contract it will consume, so story battles can slot in with no engine " +
        "change when that work starts.",
      detail: "docs/08 §4 — map · spawns · victory/defeat · events · loot · seed",
      pillClass: "plan",
      pillLabel: "NOT STARTED",
    },
  ] satisfies SystemCard[],

  /** The three customization-spine cells. */
  spineCells: [
    { n: "4 of 5", k: "Chassis slots live", sub: "primary · secondary · support · reaction — movement is the last inert slot" },
    { n: "AP", k: "Job / skill trees", sub: "directed progression · permanent mastery bonuses" },
    { n: "×", k: "Hybrid / fusion jobs", sub: "the recombination layer — curated, not the full N² web" },
  ] satisfies SpineCell[],

  /** KPI tiles (labels only — values are derived). Order is the render order. */
  kpis: [
    { key: "jobs", label: "Jobs" },
    { key: "abilities", label: "Abilities" },
    { key: "traitsStatus", label: "Traits+Status" },
    { key: "builds", label: "Unit builds" },
    { key: "encounters", label: "Encounters" },
    { key: "adrs", label: "ADRs" },
  ],

  /** Roadmap phases (P0→P4). */
  roadmap: [
    { id: "P0", title: "Core loop", blurb: "Grid · CT scheduler · seeded RNG · serializable state · formula vectors.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P1", title: "Chassis + data", blurb: "5-slot loadout · data-driven schemas · AP purchase · base job set.", state: "done", tag: "LANDED", tagClass: "ok" },
    { id: "P2", title: "Customization depth", blurb: "Trees · mastery · respec · <b>the diversity gate</b> — the balance safety net.", state: "active", tag: "IN PROGRESS", tagClass: "accent" },
    { id: "P3", title: "Enhancements", blurb: "Hybrid/fusion jobs · rewind UI · scan · speed toggle.", state: "next", tag: "PLANNED", tagClass: "plan" },
    { id: "P4", title: "Content &amp; polish", blurb: "Encounter suite · balance passes · difficulty · onboarding · sharing.", state: "next", tag: "PLANNED", tagClass: "plan" },
  ] satisfies RoadmapPhase[],

  /** "What's next" — ordered by leverage. */
  nextSteps: [
    {
      rank: "01",
      title: "Wake the movement slot",
      badge: "recommended",
      body:
        "<b>One equip slot still does nothing.</b> Support went live first (<b>ADR-0017</b>, variety " +
        "<b>5 &rarr; 6</b>), reactions second (<b>ADR-0019</b>) &mdash; the same defect twice, in the same " +
        "file, one slot over: a slot that type-checks its input and then discards it looks identical to a " +
        "working one. <b>Movement is held back by scope, not by a missing mechanic.</b> Eight of fifteen " +
        "builds equip Move+2, so switching it on hands more than half the roster extra reach at once, on a " +
        "roster whose seventh identity sits exactly on the viability floor. That is a measurement, not a " +
        "refactor. Every authored movement ability is already listed with its reason, and an A/B test asserts " +
        "the slot changes nothing &mdash; that test is what must go red when this lands.",
      chip: "1 dead slot",
      recommended: true,
    },
    {
      rank: "02",
      title: "Provoke / threat",
      badge: null,
      body:
        "An independent medium slice that retires a named manifest exclusion: a <b>threat</b> mechanic unlocks " +
        "the aggro-tank, whose identity the greedy probe cannot express today because nothing makes it worth " +
        "attacking. Hardens the gate's teeth; the N gain is build-dependent.",
      chip: "+1 build",
      recommended: false,
    },
    {
      rank: "03",
      title: "Beyond the job roster",
      badge: null,
      body:
        "The job roster is being deprioritized. <b>All 7 signature prefixes the roster can express are now " +
        "measured identities</b>, so there is zero slack: any regression fails the gate. " +
        "The last one toward the <span class=\"mono\">8</span>-archetype release bar comes from a new " +
        "signature prefix (new jobs — deferred) or the unblocks above; focus shifts to other game systems. Note " +
        "<b>MP enforcement</b> is the one lever that <em>lowers</em> N — both <span class=\"mono\">white-magic.</span> " +
        "and <span class=\"mono\">summon.</span> currently ride unenforced MP.",
      chip: "pivot",
      recommended: false,
    },
  ] satisfies NextStep[],

  /** Static footer bits (the ADR count is appended live). */
  footer: ["the-unseen-hand-turn-based", "· TypeScript · Vitest · Zod · Vite", "· determinism = P0", "· docs/ is the source of truth"],
} as const;
