/**
 * Public surface of the pure, headless simulation core (docs/05).
 *
 * Nothing in `src/sim/**` may import from a render/UI/IO layer — the sim must
 * stay unit-testable against the formula vectors and free of nondeterminism
 * (ADR-0004, sim-determinism-guard skill).
 */

export { SeededRng, type RngState } from "./rng.js";
export {
  SCHEMA_VERSION,
  MIN_SUPPORTED_SCHEMA_VERSION,
  BattleStateSchema,
  GridStateSchema,
  TileSchema,
  PositionSchema,
  FacingSchema,
  StatusFlagSchema,
  GenderSchema,
  ZodiacSignSchema,
  ElementSchema,
  WeaponFormulaSchema,
  WeaponSchema,
  EvasionSchema,
  ZodiacProfileSchema,
  UnitStateSchema,
  ChargeEffectSchema,
  ChargedActionStateSchema,
  TurnLogEntrySchema,
  SchemaVersionError,
  MIGRATIONS,
  createBattleState,
  makeFlatTiles,
  defaultUnit,
  serialize,
  deserialize,
  rngFor,
  rngStateOf,
  type BattleState,
  type GridState,
  type Tile,
  type Position,
  type Facing,
  type StatusFlag,
  type Gender,
  type ZodiacSign,
  type Element,
  type WeaponFormula,
  type Weapon,
  type Evasion,
  type ZodiacProfile,
  type UnitState,
  type ChargeEffect,
  type ChargedActionState,
  type TurnLogEntry,
  type CreateBattleStateOptions,
  type Migration,
} from "./state.js";
export {
  inBounds,
  tileIndex,
  tileAt,
  moveRange,
  relativeFacing,
  FACING_VECTOR,
  OPPOSITE_FACING,
} from "./grid.js";
export {
  HASTE_FACTOR,
  SLOW_FACTOR,
  TURN_THRESHOLD,
  CT_COST_MOVE_AND_ACT,
  CT_COST_ONE,
  CT_COST_WAIT,
  ctRateOfUnit,
  ctRateOfCharge,
  tieBreak,
  advanceToNextTurn,
  settleTurn,
  type ActiveActor,
  type NextTurn,
} from "./scheduler.js";
export {
  weaponBaseDamage,
  magicDamage,
  applyZodiac,
  applyProtect,
  applyShell,
  hitChance,
  zodiacCompatibility,
  type ZodiacTier,
} from "./formulas.js";
export {
  resolveAttack,
  tickCrystal,
  CRYSTAL_TIMER_START,
  type AttackOptions,
  type AttackOutcome,
  type ResolveResult,
  type CrystalResult,
} from "./resolve.js";
export {
  declareCharge,
  resolveCharge,
  CHARGE_INTERRUPT_STATUSES,
  type ChargeResolution,
  type ChargeOutcome,
  type ChargeResolveResult,
  type DeclareChargeInput,
} from "./charge.js";
export {
  CommandSchema,
  applyCommand,
  replay,
  replaySteps,
  type Command,
} from "./driver.js";
export {
  AbilityTypeSchema,
  AbilityFormulaSchema,
  RangeBoxSchema,
  AbilitySchema,
  BattleAbilitySchema,
  type AbilityType,
  type AbilityFormula,
  type RangeBox,
  type Ability,
  type BattleAbility,
} from "./ability.js";
export {
  SkillTreeNodeSchema,
  StatGrowthSchema,
  MasteryBonusSchema,
  JobSchema,
  type SkillTreeNode,
  type StatGrowth,
  type MasteryBonus,
  type Job,
} from "./job.js";
export {
  StatusKindSchema,
  StatusEffectSchema,
  type StatusKind,
  type StatusEffect,
} from "./status.js";
export {
  ROSTER_SCHEMA_VERSION,
  MIN_SUPPORTED_ROSTER_SCHEMA_VERSION,
  ROSTER_MIGRATIONS,
  RosterSchemaVersionError,
  RawStatsSchema,
  UnitRecordSchema,
  defaultUnitRecord,
  serializeRecord,
  deserializeRecord,
  type RawStats,
  type UnitRecord,
  type RosterMigration,
} from "./roster.js";
export {
  learnedNodeIds,
  canLearn,
  learnAbility,
  isMastered,
  checkMastery,
  changeJob,
  awardAp,
  ApRewardSchema,
  BASE_AP_GRANT,
  AP_PER_ACTION,
  ACTION_AP_CAP,
  type CanLearnResult,
  type ApReward,
} from "./progression.js";
export {
  LoadoutSlotSchema,
  LoadoutSchema,
  emptyLoadout,
  primaryCommand,
  setLoadoutSlot,
  setLoadoutTraits,
  equippedSecondaryAbilities,
  type LoadoutSlot,
  type Loadout,
} from "./loadout.js";
export {
  CONTENT_SCHEMA_VERSION,
  MIN_SUPPORTED_CONTENT_SCHEMA_VERSION,
  BASELINE_SKILLSETS,
  CONTENT_MIGRATIONS,
  ContentSchemaVersionError,
  ContentIntegrityError,
  ContentPackSchema,
  loadContentPack,
  type ContentMigration,
  type ContentPack,
  type ContentRegistry,
} from "./content.js";
