/**
 * Public surface of the pure, headless simulation core (docs/05).
 *
 * Nothing in `src/sim/**` may import from a render/UI/IO layer — the sim must
 * stay unit-testable against the formula vectors and free of nondeterminism
 * (ADR-0004, sim-determinism-guard skill).
 */

export { SeededRng, type RngState } from "./rng.js";
export {
  SCHEMA_VERSION,
  MIN_SUPPORTED_SCHEMA_VERSION,
  BattleStateSchema,
  GridStateSchema,
  TileSchema,
  PositionSchema,
  FacingSchema,
  StatusFlagSchema,
  ActiveStatusSchema,
  PERMANENT_STATUS_CT,
  GenderSchema,
  ZodiacSignSchema,
  ElementSchema,
  WeaponFormulaSchema,
  WeaponSchema,
  EvasionSchema,
  ZodiacProfileSchema,
  UnitStateSchema,
  ChargeEffectSchema,
  ChargedActionStateSchema,
  TurnLogEntrySchema,
  SchemaVersionError,
  MIGRATIONS,
  createBattleState,
  makeFlatTiles,
  defaultUnit,
  basicAttackFrom,
  BASIC_ATTACK_ID,
  isBasicAttack,
  legacyActiveStatus,
  makeActiveStatus,
  serialize,
  deserialize,
  rngFor,
  rngStateOf,
  type BattleState,
  type GridState,
  type Tile,
  type Position,
  type Facing,
  type StatusFlag,
  type ActiveStatus,
  type Gender,
  type ZodiacSign,
  type Element,
  type WeaponFormula,
  type Weapon,
  type Evasion,
  type ZodiacProfile,
  type UnitState,
  type ChargeEffect,
  type ChargedActionState,
  type TurnLogEntry,
  type CreateBattleStateOptions,
  type Migration,
} from "./state.js";
export {
  inBounds,
  tileIndex,
  tileAt,
  moveRange,
  inAbilityRange,
  relativeFacing,
  FACING_VECTOR,
  OPPOSITE_FACING,
} from "./grid.js";
export {
  HASTE_FACTOR,
  SLOW_FACTOR,
  TURN_THRESHOLD,
  CT_COST_MOVE_AND_ACT,
  CT_COST_ONE,
  CT_COST_WAIT,
  ctRateOfUnit,
  ctRateOfCharge,
  tieBreak,
  advanceToNextTurn,
  settleTurn,
  type ActiveActor,
  type NextTurn,
} from "./scheduler.js";
export {
  weaponBaseDamage,
  magicDamage,
  applyZodiac,
  applyProtect,
  applyShell,
  hitChance,
  zodiacCompatibility,
  type ZodiacTier,
} from "./formulas.js";
export {
  resolveAttack,
  resolveAbility,
  attackDamage,
  abilityDamage,
  tickCrystal,
  tryReaction,
  CRYSTAL_TIMER_START,
  type AttackOptions,
  type AttackOutcome,
  type ReactionOutcome,
  type ResolveResult,
  type CrystalResult,
} from "./resolve.js";
export {
  SupportEffectSchema,
  applySupportEffect,
  applySupportToAbility,
  DEFERRED_SUPPORT_EFFECTS,
  type SupportEffect,
} from "./support.js";
export {
  ReactionKindSchema,
  ReactionEffectSchema,
  ReactionStateSchema,
  DEFERRED_REACTION_EFFECTS,
  type ReactionKind,
  type ReactionEffect,
  type ReactionState,
} from "./reaction.js";
export {
  declareCharge,
  resolveCharge,
  applyStatusToUnit,
  statusInterruptsCharge,
  type ChargeResolution,
  type ChargeOutcome,
  type ChargeResolveResult,
  type DeclareChargeInput,
} from "./charge.js";
export {
  CommandSchema,
  advanceToDecision,
  advanceToDecisionDetailed,
  applyCommand,
  applyCommandDetailed,
  replay,
  replaySteps,
  type Command,
  type Decision,
  type ResolutionEvent,
  type AppliedCommand,
} from "./driver.js";
export {
  AbilityTypeSchema,
  AbilityFormulaSchema,
  RangeBoxSchema,
  AbilitySchema,
  BattleAbilitySchema,
  type AbilityType,
  type AbilityFormula,
  type RangeBox,
  type Ability,
  type BattleAbility,
} from "./ability.js";
export {
  SkillTreeNodeSchema,
  StatGrowthSchema,
  MasteryBonusSchema,
  JobSchema,
  type SkillTreeNode,
  type StatGrowth,
  type MasteryBonus,
  type Job,
} from "./job.js";
export {
  StatusKindSchema,
  StatusEffectSchema,
  type StatusKind,
  type StatusEffect,
} from "./status.js";
export {
  ROSTER_SCHEMA_VERSION,
  MIN_SUPPORTED_ROSTER_SCHEMA_VERSION,
  ROSTER_MIGRATIONS,
  RosterSchemaVersionError,
  RawStatsSchema,
  UnitRecordSchema,
  defaultUnitRecord,
  serializeRecord,
  deserializeRecord,
  type RawStats,
  type UnitRecord,
  type RosterMigration,
} from "./roster.js";
export {
  learnedNodeIds,
  canLearn,
  learnAbility,
  isMastered,
  checkMastery,
  changeJob,
  awardAp,
  ApRewardSchema,
  BASE_AP_GRANT,
  AP_PER_ACTION,
  ACTION_AP_CAP,
  type CanLearnResult,
  type ApReward,
} from "./progression.js";
export {
  LoadoutSlotSchema,
  LoadoutSchema,
  emptyLoadout,
  primaryCommand,
  setLoadoutSlot,
  setLoadoutTraits,
  equippedSecondaryAbilities,
  type LoadoutSlot,
  type Loadout,
} from "./loadout.js";
export {
  ScalarModSchema,
  EvasionModSchema,
  MoveModSchema,
  TraitEffectSchema,
  TraitSchema,
  applyTraitEffects,
  type ScalarMod,
  type EvasionMod,
  type MoveMod,
  type TraitEffect,
  type Trait,
  type TraitStatBase,
} from "./trait.js";
export {
  CONTENT_SCHEMA_VERSION,
  MIN_SUPPORTED_CONTENT_SCHEMA_VERSION,
  BASELINE_SKILLSETS,
  DEFERRED_SKILLSETS,
  DEFERRED_ACTIONS,
  CONTENT_MIGRATIONS,
  ContentSchemaVersionError,
  ContentIntegrityError,
  ContentPackSchema,
  loadContentPack,
  type ContentMigration,
  type ContentPack,
  type ContentRegistry,
} from "./content.js";
export {
  buildBattleUnit,
  toBattleAbility,
  buildBattleState,
  DEFERRED_MOVEMENT_EFFECTS,
  type BuildUnitInput,
  type BuildBattleGridOptions,
} from "./build.js";
export {
  ConditionSchema,
  evalCondition,
  evalTerminal,
  winningTeamOf,
  type Condition,
  type Outcome,
  type TerminalVerdict,
  type TerminalCounters,
} from "./condition.js";
export {
  ENCOUNTER_SCHEMA_VERSION,
  MIN_SUPPORTED_ENCOUNTER_SCHEMA_VERSION,
  ENCOUNTER_MIGRATIONS,
  EncounterSchemaVersionError,
  ControllerSchema,
  UnitSourceSchema,
  TeamSchema,
  PlacementSchema,
  EncounterGridSchema,
  EncounterSchema,
  parseEncounter,
  loadEncounter,
  type Controller,
  type UnitSource,
  type Team,
  type Placement,
  type EncounterGrid,
  type Encounter,
  type EncounterMigration,
  type RecordMap,
  type SlotAssignment,
  type EncounterResolver,
} from "./encounter.js";
export { decideBalanceProbe } from "./ai.js";
export {
  runEncounter,
  runEncounterDetailed,
  runFromState,
  emptyContribution,
  seedContributions,
  accountEvents,
  teamReports,
  assembleReport,
  type ReportTallies,
  type RunReport,
  type RunResult,
  type TeamReport,
  type UnitContribution,
  type RunConfig,
  type RunOptions,
} from "./harness.js";
export {
  MEASURABLE,
  EXCLUDED,
  OPPOSITION_BUILD_IDS,
  FILLER_BUILD_ID,
  FILLER_COUNT,
  CANDIDATE_SLOT,
  WIN_CEIL_TICKS,
  VIABLE_MIN_MAPS,
  DIVERSITY_TARGET_N,
  DEFAULT_BAND,
  buildGauntletEncounter,
  runGauntlet,
  computeDiversityReport,
  inBand,
  type MeasurableEntry,
  type GauntletRun,
  type GauntletMap,
  type RunGauntletParams,
  type BandConfig,
  type BuildGateStat,
  type DiversityReport,
} from "./gauntlet.js";

// ── Campaign container + persistence (docs/11 M0) ────────────────────────────
export {
  CAMPAIGN_SCHEMA_VERSION,
  MIN_SUPPORTED_CAMPAIGN_SCHEMA_VERSION,
  CAMPAIGN_MIGRATIONS,
  CampaignSchemaVersionError,
  CampaignDefSchema,
  CampaignSaveSchema,
  CampaignBattleSchema,
  CampaignStatusSchema,
  CampaignHistoryEntrySchema,
  parseCampaign,
  startCampaign,
  currentBattle,
  applyBattleResult,
  retryBattle,
  updatePartyMember,
  serializeCampaign,
  deserializeCampaign,
  type CampaignDef,
  type CampaignSave,
  type CampaignBattle,
  type CampaignStatus,
  type CampaignHistoryEntry,
  type CampaignMigration,
  type BattleResult,
} from "./campaign.js";
export {
  runCampaign,
  runCampaignBattle,
  campaignBattleRecords,
  loadCampaignBattle,
  deriveRewards,
  resolveCampaignBattle,
  type LoadedCampaignBattle,
  type CampaignRunResult,
  type CampaignRunOptions,
  type CampaignBattleRun,
  type EncounterMap,
} from "./campaign-run.js";

// ── The story seam (docs/11 M0 item 4, docs/08 §4 contract) ──────────────────
export {
  STORY_SCHEMA_VERSION,
  STORY_MIGRATIONS,
  STORY_MOMENTS,
  StorySchemaVersionError,
  StoryPackSchema,
  StoryEntrySchema,
  StoryBeatSchema,
  StoryMomentSchema,
  parseStoryPack,
  storyBeat,
  storyEntry,
  storyCoverage,
  type StoryPack,
  type StoryEntry,
  type StoryBeat,
  type StoryMoment,
  type StoryMigration,
} from "./story.js";
